version: '3'

services:
    app_php_fpm:
        build:
            context: .
            dockerfile: dockerFiles/dockerfile-app
        container_name: app_php_fpm
        working_dir: /app/
        volumes:
            -   ./:/app/
    app_service:
        build:
            context: .
            dockerfile: dockerFiles/dockerfile-service
        container_name: app_service
        working_dir: /app/
        tty: true
        ports:
            -   "2022:80"
        volumes:
            -   ./:/app
            -   ./docker/dev/server.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=app-service.local
networks:
    default:
        external:
            name: local_network

