apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    tier: backend
data:
  nginx.conf: |
          server {
                    index index.php index.html;
                    root /app/public;

                    location / {
                        try_files $uri $uri/ /index.php?$args;
                    }

                    location ~ \.php$ {
                        allow all;
                        try_files $uri =404;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass app-laravel:9000;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        include /etc/nginx/fastcgi_params;
                      }
                }

