apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: nginx-conf
    layer: frontend
data:
  default.conf: |
          server {
              listen 80 default_server;
              listen [::]:80;
              server_name _;
              server_tokens off;
              access_log off;
              root /var/www/html;
              index index.php;

              proxy_read_timeout 300;
              proxy_connect_timeout 300;
              proxy_send_timeout 300;

              location / {
                try_files $uri $uri/ /index.php?$query_string;
              }

              location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass 172.17.0.4:9001;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            }
          }

