apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-laravel
      tier: backend
  template:
    metadata:
      labels:
        app: k8s-laravel
        tier: backend
    spec:
      containers:
      - name: nginx
        image: repo.alo-dev.com/docker/nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/configMap/configMap.yml
            subPath: configMap.yml
            readOnly: true
            name: config
      volumes:
      - name: config
        configMap:
          name: nginx-conf
          items:
          - key: config
            path: nginx.conf
