apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: k8s-laravel
    tier: backend
spec:
  selector:
    app: k8s-laravel
    tier: backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32003

