apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
    - protocol: TCP
      nodePort: 32002
      port: 80
      targetPort: 80
  type: LoadBalancer

