apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-laravel
      tier: backend
  template:
    metadata:
      labels:
        app: k8s-laravel
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /code
      containers:
      - name: app-laravel
        image: mshad/laravel-k8s:0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: dir
            mountPath: /code
        env:
          - name: APP_NAME
            value: "test-laravel-k8s"
          - name: APP_ENV
            value: "development"
          - name: APP_KEY
            value: "base64:cZ7e0d4RO7v6TpPz+Z0mE6PAkGeOFj66lRQAuRc5QmY="
          - name: APP_DEBUG
            value: "true"
