apiVersion: v1
kind: Service
metadata:
  name: app-laravel
  labels:
    app: app-laravel
    tier: backend
spec:
  selector:
    app: app-laravel
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
