apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-laravel
  labels:
    app: app-laravel
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-laravel
      tier: backend
  template:
    metadata:
      labels:
        app: app-laravel
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /app
      containers:
      - name: app-laravel
        image: 470md2987md/lv-k8s:0.0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dir
          mountPath: /var/www/html
        env:
          - name: APP_NAME
            value: "test-laravel-k8s"
          - name: APP_ENV
            value: "development"
          - name: APP_KEY
            value: "base64:cZ7e0d4RO7v6TpPz+Z0mE6PAkGeOFj66lRQAuRc5QmY="
          - name: APP_DEBUG
            value: "true"
