apiVersion: v1
kind: Service
metadata:
  name: php-svc
  labels:
    app: k8s-laravel
    tier: backend
spec:
  selector:
    app: php-svc
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
